### PR TITLE
Express routes

### LINKED ISSUE #1: Add a route to query session information
Suggested route: `GET /api/session`
It should return any pertinent session information, such as the email of the user currently logged in.

### LINKED ISSUE #3: Add a route to register users
Suggested route: `POST /api/user`
This function should check against the database to ensure a unique email, then hash the password.

### LINKED ISSUE #7: Add route to serve the web files
Suggested route: `/`
Set up the Makefile to deploy and run the site.

### PR DESCRIPTION
**Pull request by WhitingJarod**
Rewrite the backend to use Express. Documentation for Elysia isn't up to snuff, especially for developers currently learning the nuances of Typescript.

Additionally, the rewrite has provided a chance to restructure and reorganize the server code.

Closes #1 
Closes #3 
Closes #7

### CODE REVIEW

**Comment by WhitingJarod** [comment]
Closes #3
Closes #7 
Closes #1

**Comment by WhitingJarod** [comment]
Not all routes are implemented, but all the routes we previously had in Elysia have been re-written.

**Comment by WhitingJarod** [comment]
@astonhaycock
Let me know if there's anything I need to fix. We're still having formatter disputes in the client-side code, but the reformatting doesn't appear to affect anything major.

This PR also adds comments to the newly-rewritten code.

**Review by astonhaycock — APPROVED** [review]
Looks great!

**Pull request merged**
